#================================
data_config:
    positive_file: ../data/train/pubchem.smi
    stereo: true
#======= Hyperparameters ========
model_parameters:
    hidden_size: 1024
    n_layers: 4
    dropout: 0.2
#================================
train_parameters:
    init_model: null
    lr: 0.0001
    lr_decay: 0.99
